# Generated by Django 4.2 on 2023-06-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Order Seen', 'Order Seen'), ('Packaging', 'Packaging'), ('On Delivering', 'On Delivering'), ('Order Cancelled', 'Order Cancelled'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
